# Generated by Django 6.0.6 on 2026-06-09 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('cpf', models.CharField(max_length=15, unique=True)),
                ('nome_mae', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('status_matricula', models.BooleanField(default=False)),
                ('certidao_nascimento', models.FileField(blank=True, null=True, upload_to='certidoes/')),
                ('arquivo_identidade', models.FileField(blank=True, null=True, upload_to='identidades/')),
                ('comprovante_residencia', models.FileField(blank=True, null=True, upload_to='comprovantes/')),
                ('foto_3x4', models.ImageField(blank=True, null=True, upload_to='fotos_3x4/')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aluno', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
